export type IconTypeName =
  | 'lock'
  | 'trash'
  | 'plus'
  | 'pixel'
  | 'dogs'
  | 'notcoin'
  | 'toncoin'
  | 'forwardArrow'
  | 'gatewayBot'
  | 'doubleChevron'
  | 'share'
  | 'trash'
  | 'check'
  | 'cross'
  | 'chevron'
  | 'eyeCrossed'
  | 'eye'
  | 'connectWallet'
  | 'toncoin'
  | 'premium'
  | 'whitelist'
  | 'externalSource'
  | 'emoji'
  | 'jetton'
  | 'nftCollection'
  | 'stickers'
  | 'gifts'
  | 'checkUnable'
  | 'completed'
  | 'sortArrows'
  | 'checkmark'

export type IconSize = 112 | 100 | 40 | 28 | 24 | 20 | 18 | 16 | 12 | 7
